#pragma once

#include "CoreMinimal.h"

// Export the logging category so other modules can use it
WINDWALKER_PRODUCTIONS_SHAREDDEFAULTS_API DECLARE_LOG_CATEGORY_EXTERN(LogInteractableSubsystem, Log, All);
WINDWALKER_PRODUCTIONS_SHAREDDEFAULTS_API DECLARE_LOG_CATEGORY_EXTERN(LogInteraction, Log, All);
WINDWALKER_PRODUCTIONS_SHAREDDEFAULTS_API DECLARE_LOG_CATEGORY_EXTERN(LogInventoryInteractableSystem, Log, All);
WINDWALKER_PRODUCTIONS_SHAREDDEFAULTS_API DECLARE_LOG_CATEGORY_EXTERN(LogDebugSystem, Log, All);